name: linkless
description: "LinkLess - Never forget a connection"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  phone_form_field: ^10.0.17
  pinput: ^6.0.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
